### PR TITLE
Nethcti ports

### PR DESCRIPTION
**Pull request by Stell0**
https://github.com/nethesis/ns8-nethvoice/issues/35

### CODE REVIEW

**Review by gsanchietti — COMMENTED** [review]
I'm not sure this is the right approach.
Maybe it's better to drop `--host network` and expose only the required ports (NETHCTI_TCP_PORT and NETHCTI_TLS_PORT).

Did you try?

**Comment by Stell0** [comment]
no, I'll try it

**Comment by Stell0** [comment]
tried to remove network=host [here](https://github.com/nethesis/ns8-nethvoice/pull/39) but http_proxy for some reason doesn't properly work. I propose to keep it as network=host @gsanchietti

**Comment by gsanchietti** [comment]
It's ok for me

**Pull request merged**
